/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gym;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Erik
 */
public class regismem extends javax.swing.JFrame {

    conexion cc=new conexion();
    Connection con = cc.conectar();
    conexion cos = new conexion();
    String cons="",cons2="",fechas="",fechas2="";
    int numero=0;
    float total=0;
    /**
     * Creates new form sesion
     */
    public regismem() {
        initComponents();
        this.setIconImage(new ImageIcon(getClass().getResource("/imagenes/Recurso 2.png")).getImage());
        cargarc();
        Date date = new Date();
        DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        fecha.setText(dateFormat.format(date));
        //acti.setModel(cos.objeto());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
     public void agregarusuario(){
         String act = (String) clientes.getSelectedItem();
         String id="";
         initComponents();
         String sql="insert into membresia (id_membresia, id_cliente, actividad, actividad2, status, pago, inicio, vencimiento) values(?,?,?,?,?,?,?,?)";
         try{
             PreparedStatement pst=con.prepareStatement(sql);
             pst.setString(1, numero+"");
             String sql1="select * from cliente where nombre='"+act+"'";   
            try {
                PreparedStatement pst1;
                pst1 = con.prepareStatement(sql1);
                ResultSet s=pst.executeQuery(sql1);
                while(s.next()){
                    id=s.getString("id_cliente");
                }
               
            } catch (SQLException ex) {
                Logger.getLogger(regismem.class.getName()).log(Level.SEVERE, null, ex);
            }
             pst.setString(2, id);
             sql1="select * from actividad where actividad='"+cons+"'";   
            try {
                PreparedStatement pst1;
                pst1 = con.prepareStatement(sql1);
                ResultSet s=pst.executeQuery(sql1);
                while(s.next()){
                    id=s.getString("id_act");
                }
               
            } catch (SQLException ex) {
                Logger.getLogger(regismem.class.getName()).log(Level.SEVERE, null, ex);
            }
             pst.setString(3, id);
             sql1="select * from actividad where actividad='"+cons2+"'";    
            try {
                PreparedStatement pst1;
                pst1 = con.prepareStatement(sql1);
                ResultSet s=pst.executeQuery(sql1);
                while(s.next()){
                    id=s.getString("id_act");
                }
               
            } catch (SQLException ex) {
                Logger.getLogger(regismem.class.getName()).log(Level.SEVERE, null, ex);
            }
             pst.setString(4, id);
             pst.setString(5, "Activo");
             pst.setString(6, total+"");
             pst.setString(7, fechas);
             pst.setString(8, fechas2);
             pst.executeUpdate();
             JOptionPane.showMessageDialog(null, "registro exitoso");
         }catch(Exception e){
             JOptionPane.showMessageDialog(null, "error"+e.getMessage());
             
         }
         this.dispose();         
     }
     public void cargarc(){
         String sql="select actividad, costo from actividad";
         String sql2="select id_cliente, nombre from cliente";
         
        try {
            PreparedStatement pst;
            PreparedStatement pst1;
            pst = con.prepareStatement(sql2);
            ResultSet sr=pst.executeQuery(sql2);
            pst1 = con.prepareStatement(sql);
            ResultSet s=pst1.executeQuery(sql);
            clientes.removeAllItems();
            act1.removeAllItems();
            act2.removeAllItems();
            while(s.next()){
                act1.addItem(s.getString(1));
                act2.addItem(s.getString(1));
            }
            while(sr.next()){
                clientes.addItem(sr.getString(2));
            }
        } catch (SQLException ex) {
            Logger.getLogger(regismem.class.getName()).log(Level.SEVERE, null, ex);
        }
         
     }
     public void aleatorio(){
         int band=0;
         do{
                
                try {
                    numero = (int)Math.round(Math.random()*(9999-1000)+1000);
                    String sql2="select * from cliente where id_cliente='"+numero+"'";
                    PreparedStatement pst;
                    pst = con.prepareStatement(sql2);
                    ResultSet sr=pst.executeQuery(sql2);
                    if(sr.next() || sr.next()){
                        band=0;
                    }else{
                         band=1;
                    }
                } catch (SQLException ex) {
                    Logger.getLogger(regiscliente.class.getName()).log(Level.SEVERE, null, ex);
                }
                
            
            
         }while(band==0);
         id.setText(numero+"");
     }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItem2 = new javax.swing.JRadioButtonMenuItem();
        jLabel1 = new javax.swing.JLabel();
        fin = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        fecha = new javax.swing.JTextField();
        pagoin = new javax.swing.JTextField();
        clientes = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        act1 = new javax.swing.JComboBox<>();
        generar = new javax.swing.JButton();
        act2 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        calcular = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        monto = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        label = new javax.swing.JLabel();
        pagar = new javax.swing.JButton();
        pagog = new javax.swing.JLabel();
        fechafin = new javax.swing.JLabel();
        label1 = new javax.swing.JLabel();
        cambio = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        jRadioButtonMenuItem2.setSelected(true);
        jRadioButtonMenuItem2.setText("jRadioButtonMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("registro de membresia");

        fin.setText("terminar");
        fin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finActionPerformed(evt);
            }
        });

        jLabel2.setText("id membresia");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/2b22e1ec-02de-477c-b903-69d0b29321a3_200x200.png"))); // NOI18N
        jLabel4.setText("jLabel4");

        id.setText("genere numero de cliente ->");
        id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idActionPerformed(evt);
            }
        });

        fecha.setName(""); // NOI18N
        fecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fechaActionPerformed(evt);
            }
        });

        pagoin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pagoinActionPerformed(evt);
            }
        });
        pagoin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                pagoinKeyReleased(evt);
            }
        });

        clientes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        clientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clientesActionPerformed(evt);
            }
        });

        jLabel5.setText("id cliente");

        jLabel6.setText("actividad 1");

        act1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        generar.setText("generar");
        generar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generarActionPerformed(evt);
            }
        });

        act2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel3.setText("actividad 2");

        calcular.setText("calcular");
        calcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcularActionPerformed(evt);
            }
        });

        jLabel7.setText("pago");

        monto.setText("monto");

        jLabel9.setText("cambio");

        label.setText(" ");

        pagar.setText("pagar");
        pagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pagarActionPerformed(evt);
            }
        });

        pagog.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pagog.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        fechafin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fechafin.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        label1.setText("fecha de termino");

        cambio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cambio.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel8.setText("Fecha de inicio(yyyy-mm-dd)");

        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
        });

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton-de-informacion (1).png"))); // NOI18N
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(143, 143, 143)
                .addComponent(jLabel1))
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(label))
                    .addComponent(jLabel7)
                    .addComponent(label1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(monto)
                        .addComponent(jLabel9)))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pagog, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(fechafin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(act2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(act1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(id, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                            .addComponent(clientes, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(fecha)
                            .addComponent(pagoin)
                            .addComponent(cambio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(generar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(calcular)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(pagar)
                        .addGap(18, 18, 18)
                        .addComponent(fin)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel10)
                        .addGap(15, 15, 15))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(54, 54, 54)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(generar))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(clientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(act1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(act2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(label)
                                    .addComponent(jLabel8))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(fechafin, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 2, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(42, 42, 42))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(label1)
                                        .addGap(14, 14, 14)))))
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(pagog, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(calcular)))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pagoin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(monto))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 19, Short.MAX_VALUE)
                    .addComponent(cambio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(pagar)
                        .addComponent(fin))
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12)
                .addContainerGap())
        );

        fecha.getAccessibleContext().setAccessibleName("");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void finActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finActionPerformed
        agregarusuario();
    }//GEN-LAST:event_finActionPerformed

    private void clientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clientesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clientesActionPerformed

    private void idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idActionPerformed

    private void generarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generarActionPerformed
        aleatorio();
    }//GEN-LAST:event_generarActionPerformed

    private void pagoinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pagoinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pagoinActionPerformed

    private void fechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fechaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fechaActionPerformed

    private void calcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcularActionPerformed
        fechas = fecha.getText();  
        String[] arrayfechas = fechas.split("-");
        for (int i = 0; i < arrayfechas.length; i++) {
            System.out.println(arrayfechas[i]);
        } 
        int anio= Integer.parseInt(arrayfechas[0]);
        int mes= Integer.parseInt(arrayfechas[1]);
        int dia= Integer.parseInt(arrayfechas[2]);
        if (mes==12){
            mes=01;
            anio=anio+1;
        }else{
            mes= mes + 1;
        }
        /*recuperar costo de las actividades seleccionadas*/
        cons = act1.getSelectedItem().toString();
        cons2 = act2.getSelectedItem().toString();
        float costo1=0,costo2=0;
        String sql="select * from actividad where actividad='"+cons+"'";
        String sql1="select * from actividad where actividad='"+cons2+"'";   
        try {
            PreparedStatement pst;
            pst = con.prepareStatement(sql);
            ResultSet s=pst.executeQuery(sql);
            while(s.next()){
                costo1=s.getFloat("costo");              
            }
            if(cons2!=""){
            pst = con.prepareStatement(sql);
            ResultSet s1=pst.executeQuery(sql1);
            while(s1.next()){
                    costo2=s1.getFloat("costo");
                }
            }
        
            
            
        } catch (SQLException ex) {
            Logger.getLogger(regismem.class.getName()).log(Level.SEVERE, null, ex);
        }
        total=costo1+costo2;
        fechas2=anio+"-"+mes+"-"+dia;
        fechafin.setText(anio+"-"+mes+"-"+dia);
        pagog.setText(total+"");
        
    }//GEN-LAST:event_calcularActionPerformed

    private void pagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pagarActionPerformed
        float pag= Float.parseFloat(pagog.getText());
        float pag2= Float.parseFloat(pagoin.getText());
        float tot=pag2-pag;
        cambio.setText(tot+"");
    }//GEN-LAST:event_pagarActionPerformed

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
        informacion pass = new informacion();
        pass.setVisible(true);
    }//GEN-LAST:event_jLabel12MouseClicked

    private void pagoinKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pagoinKeyReleased
        float pag= Float.parseFloat(pagog.getText());
        float pag2= Float.parseFloat(pagoin.getText());
        float tot=pag2-pag;
        cambio.setText(tot+"");
    }//GEN-LAST:event_pagoinKeyReleased

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        informacion pass = new informacion();
        pass.setVisible(true);
    }//GEN-LAST:event_jLabel10MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(regismem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(regismem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(regismem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(regismem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new regismem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> act1;
    private javax.swing.JComboBox<String> act2;
    private javax.swing.JButton calcular;
    private javax.swing.JLabel cambio;
    private javax.swing.JComboBox<String> clientes;
    private javax.swing.JTextField fecha;
    private javax.swing.JLabel fechafin;
    private javax.swing.JButton fin;
    private javax.swing.JButton generar;
    private javax.swing.JTextField id;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem2;
    private javax.swing.JLabel label;
    private javax.swing.JLabel label1;
    private javax.swing.JLabel monto;
    private javax.swing.JButton pagar;
    private javax.swing.JLabel pagog;
    private javax.swing.JTextField pagoin;
    // End of variables declaration//GEN-END:variables
}
